export const DASHBOARD_CLIENTS = {
  WOM: 'WOM',
  CLARO: 'CLARO',
};

export const SECTION_KEYS = {
  KPI_CARDS: 'kpiCards',
  DAILY_TREND: 'dailyTrend',
  AGENT_PERFORMANCE: 'agentPerformance',
  COMMERCIAL_FUNNEL: 'commercialFunnel',
  TIKTOK_LIVE: 'tiktokLive',
  LEAD_STATUS: 'leadStatus',
  DAILY_OPERATIONAL_TABLE: 'dailyOperationalTable',
  AGENT_DETAIL_TABLE: 'agentDetailTable',
  EFFICIENCY: 'efficiency',
  ROSTER: 'roster',
  KPI_COMPLIANCE: 'kpiCompliance',
  ALERTS: 'alerts',
};

export const DEFAULT_EXPECTED_HOURS_PER_AGENT_PER_DAY = 4;
export const DEFAULT_EXPECTED_LEADS_PER_AGENT_PER_DAY = 8;
export const DEFAULT_EXPECTED_SALES_PER_AGENT_PER_DAY = 2;
export const DEFAULT_EXPECTED_CONVERSION_PERCENT = 25;
export const DEFAULT_ADHERENCE_TARGET_PERCENT = 85;

export const CLIENT_DASHBOARD_CONFIG = {
  WOM: {
    clientKey: DASHBOARD_CLIENTS.WOM,
    clientLabel: 'WOM',
    commercialUnitLabel: 'Prospectos',
    primaryLeadMetric: 'prospectsTotal',
    leadLikeMetric: 'leadLikeCount',
    enabledSections: [
      SECTION_KEYS.KPI_CARDS,
      SECTION_KEYS.DAILY_TREND,
      SECTION_KEYS.AGENT_PERFORMANCE,
      SECTION_KEYS.COMMERCIAL_FUNNEL,
      SECTION_KEYS.TIKTOK_LIVE,
      SECTION_KEYS.LEAD_STATUS,
      SECTION_KEYS.EFFICIENCY,
      SECTION_KEYS.DAILY_OPERATIONAL_TABLE,
      SECTION_KEYS.AGENT_DETAIL_TABLE,
      SECTION_KEYS.ALERTS,
    ],
    kpiCardKeys: [
      'leadLikeCount',
      'salesTotal',
      'conversionRate',
      'liveHours',
      'adherenceRate',
      'activeAgents',
      'views',
      'peakViewers',
    ],
    extraKpis: [
      'prospectsPerAgent',
      'salesPerAgent',
      'conversionPerAgent',
      'liveMinutesPerAgent',
      'liveBlocksPerAgent',
      'prospectsPerLiveHour',
      'salesPerLiveHour',
      'nonSaleRate',
      'topNonSaleReasons',
      'agentsWithoutConnectionWithProspects',
      'agentsConnectedWithoutSales',
      'viewsToProspectsRate',
      'viewsToSalesRate',
      'uniqueViewersToProspectsRate',
      'uniqueViewersToSalesRate',
    ],
    expectedHoursPerAgentPerDay: DEFAULT_EXPECTED_HOURS_PER_AGENT_PER_DAY,
    expectedLeadsPerAgentPerDay: DEFAULT_EXPECTED_LEADS_PER_AGENT_PER_DAY,
    expectedSalesPerAgentPerDay: DEFAULT_EXPECTED_SALES_PER_AGENT_PER_DAY,
    expectedConversionPercent: DEFAULT_EXPECTED_CONVERSION_PERCENT,
    adherenceTargetPercent: DEFAULT_ADHERENCE_TARGET_PERCENT,
  },
  CLARO: {
    clientKey: DASHBOARD_CLIENTS.CLARO,
    clientLabel: 'Claro',
    commercialUnitLabel: 'Leads',
    primaryLeadMetric: 'leadsTotal',
    leadLikeMetric: 'leadLikeCount',
    enabledSections: [
      SECTION_KEYS.KPI_CARDS,
      SECTION_KEYS.DAILY_TREND,
      SECTION_KEYS.AGENT_PERFORMANCE,
      SECTION_KEYS.COMMERCIAL_FUNNEL,
      SECTION_KEYS.TIKTOK_LIVE,
      SECTION_KEYS.LEAD_STATUS,
      SECTION_KEYS.ROSTER,
      SECTION_KEYS.KPI_COMPLIANCE,
      SECTION_KEYS.DAILY_OPERATIONAL_TABLE,
      SECTION_KEYS.AGENT_DETAIL_TABLE,
      SECTION_KEYS.ALERTS,
    ],
    kpiCardKeys: [
      'leadLikeCount',
      'salesTotal',
      'conversionRate',
      'liveHours',
      'adherenceRate',
      'activeAgents',
      'views',
      'peakViewers',
    ],
    extraKpis: [
      'expectedLiveHours',
      'liveHoursGap',
      'adherenceRate',
      'activeAgentsByDay',
      'totalRoster',
      'activeRoster',
      'inactiveRoster',
      'activeRosterRate',
      'avgConnectionPerAgent',
      'leadsPerActiveAgent',
      'salesPerActiveAgent',
      'kpiComplianceByEps',
      'kpiComplianceByAgent',
      'agentsUnderAdherenceTarget',
      'agentsWithoutDailyRecords',
      'realVsExpectedLiveHours',
      'realVsExpectedLeads',
      'realVsExpectedSales',
      'realVsExpectedConversion',
      'agentsConnectedWithoutSales',
    ],
    expectedHoursPerAgentPerDay: DEFAULT_EXPECTED_HOURS_PER_AGENT_PER_DAY,
    expectedLeadsPerAgentPerDay: DEFAULT_EXPECTED_LEADS_PER_AGENT_PER_DAY,
    expectedSalesPerAgentPerDay: DEFAULT_EXPECTED_SALES_PER_AGENT_PER_DAY,
    expectedConversionPercent: DEFAULT_EXPECTED_CONVERSION_PERCENT,
    adherenceTargetPercent: DEFAULT_ADHERENCE_TARGET_PERCENT,
  },
};

export function resolveClientDashboardConfig(client) {
  return CLIENT_DASHBOARD_CONFIG[client] ?? CLIENT_DASHBOARD_CONFIG.WOM;
}
